### ISSUE TITLE
最终的模型

### ISSUE THREAD

**Issue by zangtuo** [1suancaiyu/ICE-GCN#1]
你好，我想问一下最终的模型是ICDE-GCN.py吗？感谢~

**Comment by 1suancaiyu** [comment]
嗯嗯，是的，感谢关注。但是我最终的代码不是放到这个repo里面的，后面，我会整理更新到https://github.com/shuxiwang/ICE-GCN 谢谢。

**Comment by zangtuo** [comment]
感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1suancaiyu/ICE-GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月22日(星期六) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1suancaiyu/ICE-GCN] 最终的模型 (Issue #1)





 
嗯嗯，是的，感谢关注。但是我最终的代码不是放到这个repo里面的，后面，我会整理更新到https://github.com/shuxiwang/ICE-GCN 谢谢。
